# Generated by Django 4.2.7 on 2023-11-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("videos", "0001_initial"),
        ("personal_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewedvideo",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videos.video"
            ),
        ),
    ]
