version: "3.8"

services:
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: leafsee
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - docker-mysql-leafsee:/var/lib/mysql
        ports:
            - "3307:3306"
volumes:
    docker-mysql-leafsee:
